### ISSUE TITLE
Update tweepy for py3.7 support

### ISSUE THREAD

**Issue by dschep** [Nick-Gottschlich/Social-Amnesia#34]
Seems the py3.7 tweepy issue has been fixed: https://github.com/tweepy/tweepy/pull/1042#issuecomment-442395665

**Comment by Nick-Gottschlich** [comment]
Awesome, thanks for the heads up! I've gone ahead and removed that note from the ReadMe

**Comment by dschep** [comment]
You'll need to also update `requirements.txt` 😉

**Comment by dschep** [comment]
great tool btw!
