### ISSUE TITLE
[Release 1.1.0] Successfully started once, fails to start afterwards

### ISSUE THREAD

**Issue by StripedPuppy** [Nick-Gottschlich/Social-Amnesia#43]
**[cx_Freeze: Python error in main script](https://user-images.githubusercontent.com/34108520/53682267-b461ee80-3ca8-11e9-96cc-b71aa81e82b1.png)**

Platform: Windows 7 x64 Professional

***

I also have another issue. I successfully logged into my Reddit account, entered my deletion parameters and I can see a [few of my comments](https://user-images.githubusercontent.com/34108520/53682372-b37d8c80-3ca9-11e9-82a0-2b5e3077358a.png), but every time I click delete I get this warning: "Please login to Reddit!" followed by an empty dialog "The following comments will be deleted:".

**Comment by Nick-Gottschlich** [comment]
I'll take a look into this, see what I can find.

**Comment by Nick-Gottschlich** [comment]
@StripedPuppy Try searching your computer for a file called "reddit_state.db". Delete that file, restart Social Amnesia, and then log back in. This might fix your issue.

**Comment by StripedPuppy** [comment]
> 
> 
> @StripedPuppy Try searching your computer for a file called "reddit_state.db". Delete that file, restart Social Amnesia, and then log back in. This might fix your issue.

That worked for me. Now the program is working as expected.
![2019-03-07 03_44_14](https://user-images.githubusercontent.com/34108520/53954597-8bb46d00-408b-11e9-8c96-d7ae41897434.png)
