### ISSUE TITLE
Correctly filling out the login form -except the password field- hangs the program

### ISSUE THREAD

**Issue by Dustie** [Nick-Gottschlich/Social-Amnesia#48]
Filling out username, Client ID and secret correctly but using a wrong password causes the program to open a browser window and then freeze:

https://www.reddit.com/api/v1/authorize?client_id=11qGJzn6bkKEpw&duration=permanent&redirect_uri=http%3A%2F%2Flocalhost%3A8080&response_type=code&scope=identity+history+read+edit&state=18111

The only way out of this seems to be to kill the program.

**Comment by Nick-Gottschlich** [comment]
Dang, thought I fixed this bug in this PR: https://github.com/Nick-Gottschlich/Social-Amnesia/pull/44

Are you using version 1.2.0?

**Comment by Dustie** [comment]
Sorry yes, 1.2.0 in Windows 10.

**Comment by Nick-Gottschlich** [comment]
Okay, I will try to take a look at this soon. Thank you for bringing this to my attention!

**Comment by Nick-Gottschlich** [comment]
Closing this out now that Version 2 of Social Amnesia has been released.
