### ISSUE TITLE
Feature request: custom text for comment edit

### ISSUE THREAD

**Issue by ksurl** [Nick-Gottschlich/Social-Amnesia#50]
shreddit is pretty much what I want but something changed on reddit and it no longer works with whitelisting subreddits. it allows custom text to be set before deleting. I have no idea what the text says now since it's deleted and I don't have the link to look at the deleted comment.

**Comment by Nick-Gottschlich** [comment]
Nice idea, right now I have either random text or "Overwritten by Social Amnesia" as the edit text options. I will look into adding a custom text option.

**Comment by ksurl** [comment]
I see thanks. is there a setting for choosing random or "Overwritten by Social Amnesia"?

**Comment by Nick-Gottschlich** [comment]
Yep! The setting that says "Edit items multiple times before deleting" will overwrite the message a couple times with random strings.

If you want custom text right this moment, you can also clone or fork the repo, go to this line of code https://github.com/Nick-Gottschlich/Social-Amnesia/blob/master/services/reddit.py#L19 and edit it to say whatever you want, then run the app from the command line with Python.

**Comment by ksurl** [comment]
Closing since a fork of shreddit seems to be compatible with reddit.
