### ISSUE TITLE
Seems to work great, but only lists a few posts and comments?

### ISSUE THREAD

**Issue by gitatmax** [Nick-Gottschlich/Social-Amnesia#63]
Hi, I'm able to authenticate with Reddit and everything, but it seems to only pick up a few posts and comments. I tested removing some old comments, it seemed to delete what I told it to there, but it's still only listing some posts and comments.

I am running Version 2.0.0-b2 (2.0.0-b2). I'm What might I be missing? Thank you.

![](https://user-images.githubusercontent.com/7244793/87856173-493fa900-c8eb-11ea-9778-20aceca5362a.png)

**Comment by Nick-Gottschlich** [comment]
Hey there! First off, it brings me great joy to see that people are using something I created and gaining value from it 😁. Thank you!!

Second, some good news, I am aware of this bug and have actually just fixed it. Reddit had a default limit of 25 items for the API call, and I was only grabbing that many. Social Amnesia will now get up to the API limit of 1000 items back (for both posts and comments).

Check out the new release and let me know if that fixes your problem! 

https://github.com/Nick-Gottschlich/Social-Amnesia/releases/tag/v2.0.0-b3

While I've got you, if you don't mind me asking, how did you find out about Social Amnesia? I don't run any analytics so I have no idea how people actually stumble upon my software.

**Comment by gitatmax** [comment]
@Nick-Gottschlich, you're welcome & thanks so much for creating this gem!

I did as you as you said and checked out the new version. It worked great, thanks again!

I came across your repository here, I think, browsing Reddit (or a Google search). I had tried out the application in version 2 and am happy to see it growing.

All the best!
