### ISSUE TITLE
32-bit support?

### ISSUE THREAD

**Issue by saieeshb** [Nick-Gottschlich/Social-Amnesia#68]
Hello, I've downloaded the .exe file and noticed that this is only for 64-bit devices. Is the support for 32-bit coming anytime soon?

**Comment by Nick-Gottschlich** [comment]
Hello @saieeshb ! Thank you for your interest in Social Amnesia!

I have just attached a 32 bit windows exe to the release page here: https://github.com/Nick-Gottschlich/Social-Amnesia/releases/tag/v2.0.2

Please let me know if that works! 😁

**Comment by saieeshb** [comment]
Thanks so much for the quick response! @Nick-Gottschlich 

It works perfectly! Tbh, I did not expect a response so quickly, so thanks again!
:smile:

**Comment by saieeshb** [comment]
Hey, Reddit worked just fine, but for some reason, I can't seem to delete my tweets on Twitter. I've tried logging in and out and, and reopening the program. It shows me the "Are you sure?" message but when I click OK, nothing happens. What might be the issue?

**Comment by Nick-Gottschlich** [comment]
@saieeshb 

Can you try to toggle the developer tools on for me:

![image](https://user-images.githubusercontent.com/10564265/89145715-4661cc80-d517-11ea-9f29-6086fd117b3f.png)

And then try to delete your tweets again, I want to see if it reports an error.

I'm worried that my app might be running over the API usage twitter allows for my account with the amount of people using it.

**Comment by saieeshb** [comment]
@Nick-Gottschlich I turned on Developer Tools and attempted to delete my tweets, and by doing that it works! The console is empty with no errors as well. Just checked and the tweets are deleted as well. Thanks! :)

**Comment by Nick-Gottschlich** [comment]
Glad to hear it works! I doubt opening the dev tools did it, must've been some temporary issue with the connection to the twitter API.

**Comment by saieeshb** [comment]
That'd probably be it. Anyways, thanks for making this! 👏👏
